function vis_draw(){var c="January February March April May June July August September October November December".split(" "),e=d3.select("#vis-graph").append("svg").attr("width",1400).attr("height",375),d=function(a){return"#FF5600 #58026D #049B15 #FFCA00 #000000 #35C0CD #F40B9B #028C7B #FF0D00 #E51743 #2F00D8 #80E800".split(" ")[a]},f=d3.scale.linear().domain([1,10]).range([50,300]),g=d3.scale.linear().domain([0,43200]).range([75,1350]),h=d3.svg.line().x(function(a){return a.x}).y(function(a){return a.y}).interpolate("linear")(_.map([1,
2,3,4,5,6,1],function(a){return{x:5*Math.sin(Math.PI/3*a),y:5*Math.cos(Math.PI/3*a)}})),b=d3.svg.line().x(function(a){return a.x}).y(function(a){return a.y}).interpolate("linear")(_.map([1,2,3,4,5,6,1],function(a){return{x:15*Math.sin(Math.PI/3*a),y:15*Math.cos(Math.PI/3*a)}})),k=function(a,m){"selector selected"==d3.select("#sel-"+a).attr("class")&!m?(d3.select("#sel-"+a).attr("class","selector"),d3.select("#group-"+a).attr("class","month"),d3.select("#sel-"+a+" path").attr("style","fill: #F9F4D2; stroke: "+
d(a))):(d3.select("#sel-"+a).attr("class","selector selected"),d3.select("#group-"+a).attr("class","month selected"),d3.select("#sel-"+a+" path").attr("style","fill: "+d(a)+"; stroke: "+d(a)))},n=d3.svg.line().x(function(a){return a.x}).y(function(a){return a.y});e.selectAll("line.ygrid").data(_.range(1,11)).enter().append("line").attr("class","ygrid").attr("class","grid").attr("x1",50).attr("x2",1380).attr("y1",function(a){return f(a)}).attr("y2",function(a){return f(a)});e.selectAll("line.xgrid").data(_.range(0,
31)).enter().append("line").attr("class","xgrid").attr("class","grid").attr("x1",function(a){return g(1440*a)}).attr("x2",function(a){return g(1440*a)}).attr("y1",20).attr("y2",330);e.selectAll("text.xlabel").data(_.range(0,31)).enter().append("text").attr("x",function(a){return g(1440*a)}).attr("y",327).attr("dx",1).attr("class","xlabel").text(function(a){return a+1});e.selectAll("text.ylabel").data([1,10]).enter().append("text").attr("x",50).attr("y",function(a){return f(a)}).attr("class","ylabel").attr("text-anchor",
"end").attr("dy",function(a){return 5>a?-7:14}).text(function(a){return 1==a?"happy":"sad"});var l=e.selectAll("g.selector").data([0,1,2,3,4,5,6,7,8,9,10,11]).enter().append("g").attr("class","selector").attr("id",function(a){return"sel-"+a}).attr("transform",function(a){return"translate("+[90+110*a,355]+")"}).on("click",function(a){k(a)});l.append("path").attr("d",b).attr("style",function(a){return"fill: #F9F4D2; stroke: "+d(a)}).text(function(a){return c[a]});l.append("text").attr("x",15).attr("y",
7).text(function(a){return c[a]});return function(a){a=_.sortBy(a,function(a){return a.time});a=_.map(a,function(a){a.y=f(a.score);var b=new Date(a.time),c=1440*(b.getDate()-1)+60*b.getHours()+b.getMinutes();a.month=b.getMonth();a.x=g(c);a.color=d(a.month);return a});a=_.values(_.reduce(a,function(a,b){var c=b.month;void 0!=a[c]?a[c].push(b):a[c]=[b];return a},{}));a=e.selectAll("g.month").data(a).enter().append("g").attr("class","month").attr("id",function(a){return"group-"+a[0].month});a.append("path").attr("d",
function(a){return n(a)}).attr("style",function(a){return"stroke: "+a[0].color}).on("click",function(a){k(a[0].month)});a.selectAll("path.point").data(function(a){return a}).enter().append("path").attr("class","point").attr("d",h).attr("transform",function(a){return"translate("+[a.x,a.y]+")"}).attr("style",function(a){return"fill: "+a.color}).on("click",function(a){d3.selectAll(".popup").remove();e.append("switch").attr("class","popup").append("foreignObject").attr("x",a.x).attr("y",a.y).attr("rx",
10).attr("ry",10).attr("width",200).attr("height",150).append("xhtml:body").html("<div class='popup'>"+a.note+"</div>");d3.selectAll("div.popup").on("click",function(a){d3.selectAll(".popup").remove()})});k((new Date).getMonth(),!0)}};function input_draw(){var c=d3.select("#input-graph").append("svg").attr("width",200).attr("height",300),e=d3.scale.linear().domain([52,248]).range([-10,10]),d=function(b){return void 0==b?0:e(b.y)},f=d3.svg.line().x(function(b){return b.x}).y(function(b){return b.y}).interpolate("basis-open"),g=function(b){return f([{x:-20,y:20+d(b)},{x:0,y:20-d(b)},{x:20,y:20+d(b)}])},h=d3.behavior.drag().on("drag",function(b,c){d3.select("g.arrow").remove();b.y+=d3.event.dy;250<b.y&&(b.y=248);50>b.y&&(b.y=52);
d3.select(this).attr("transform",function(b,c){return"translate("+[b.x,b.y]+")"});d3.select("#mouth").attr("d",g(b))}),h=c.append("g").data([{x:100,y:150}]).attr("id","smiley").attr("transform",function(b){return"translate("+[b.x,b.y]+")"}).call(h);h.append("circle").attr("cx",0).attr("cy",0).attr("r",50).attr("style","stroke:#000; stroke-width:1.5px; fill:#FFCA00");h.selectAll("circle.eye").data([-1,1]).enter().append("circle").attr("class","eye").attr("cx",function(b){return 15*b}).attr("cy",-10).attr("r",
7).attr("style","stroke:#000; stroke-width:1.5px; fill:#000");f=d3.svg.line().x(function(b){return b.x}).y(function(b){return b.y}).interpolate("basis");h.append("path").attr("id","mouth").attr("d",g).attr("style","stroke:#000; stroke-width:2px;");c=c.selectAll("g.arrow").data([0,1]).enter().append("g").attr("class","arrow").attr("transform",function(b){return"translate("+[100,150-55*(b?1:-1)]+") rotate("+180*b+")"});c.append("line").attr("x1",0).attr("x2",0).attr("y1",0).attr("y2",50);c.selectAll("line.tip").data([1,
-1]).enter().append("line").attr("class","tip").attr("x1",0).attr("x2",function(b){return 10*b}).attr("y1",50).attr("y2",40)}
function sbmt(){var c=d3.scale.linear().domain([50,250]).range([1,10]),e=document.getElementById("note").value;d3.select("svg > g#smiley").each(function(d){d=c(d.y);gapi.client.moodlog.entry.insert({score:d,note:e}).execute(function(c){console.log(c);show_vis()});d3.select("#submitbutton a").remove();d3.select("#submitbutton").append("img").attr("src","img/submit.png").attr("style","opacity: 0.2")})};var visualize;function init(){input_draw();visualize=vis_draw();gapi.client.load("moodlog","v2",function(){d3.select("#login").on("click",function(){gapi.auth.authorize({client_id:"467877166527.apps.googleusercontent.com",scope:"https://www.googleapis.com/auth/userinfo.email",immediate:!1,response_type:"token id_token"},authed)});d3.select("#login").attr("style","opacity: 1")},"https://moodlogr.appspot.com/_ah/api")}
function authed(){gapi.auth.getToken()&&(show_input(),d3.select("ul.menu").attr("style","display: block"))}function show_input(){d3.selectAll("div.content > div").attr("style","display: none");d3.selectAll("#input").attr("style","display: block");d3.selectAll(".menu > li").attr("class","");d3.select("#menu-input").attr("class","selected")}
function show_vis(){d3.selectAll("div.content > div").attr("style","display: none");d3.selectAll("#vis").attr("style","display: block");d3.selectAll(".menu > li").attr("class","");d3.select("#menu-view").attr("class","selected");gapi.client.moodlog.entries.list().execute(function(c){visualize(c.items)})}
function logout(){d3.selectAll("div.content > div").attr("style","display: none");d3.selectAll("#start").attr("style","display: block");d3.select("ul.menu").attr("style","display: none");gapi.auth.setToken(null);d3.selectAll("svg").remove();input_draw();visualize=vis_draw()}function carousel(c,e){var d=d3.selectAll(".carousel").attr("style","opacity: 0.2");d[0][c].style.opacity=1;c++;c==d[0].length&&(c=0);window.setTimeout(function(){carousel(c,e)},e)}window.onload=function(){carousel(0,5E3)};
